#!/bin/sh

echo "Cloning capi-deploy from git..."
git clone git@github.com:cleverti/capi-deploy.git

echo "Moving into deploy..."
mv capi-deploy/deploy .
mv capi-deploy/Capfile .

echo "Removing temp git dir..."
rm -rf capi-deploy

echo "All done!"

